rom bs4 import BeautifulSoup
import re
from urllib.request import urlopen, Request
from openpyxl import Workbook
import os
from datetime import datetime
import pandas
import ssl

ssl._create_default_https_context = ssl._create_unverified_context

websites = ['Saera Electric Auto Pvt. Ltd.','Knight Queen Industries Pvt. Ltd.','Goenka Electric Motor Vehicles Pvt. Ltd','Victory Electric International',
'Battery Rickshaw Sangh',
'Battery Rickshaw Sangh',
'Kuku Automotives',
'Hovel Cylinder Pvt. Ltd',
'SuperEco Automotive Co. LLP',
'Thukral Electric Bikes Pvt. Ltd',
'Lohia Auto Industries',
'U.P. Telelinks Ltd',
'Champion Poly Plast',
'CLH Gaseous Fuel Applications Pvt Ltd',
'Y C Electric Vehicle',
'Goenka Electric Motor Vehicles Pvt. Ltd',
'Electrotherm India Ltd',
'Soni E Vehicle Pvt. Ltd',
'Goodenergy India',
'Electrotherm India Ltd',
'Kuku Automotives',
'Caparo Autotech Ltd',
'SAS Motors Ltd',
'DYS Impex Pvt Ltd',
'Soni E Vehicle Pvt. Ltd',
'Champion Poly Plast',
'Volmac Engineering Pvt. Ltd',
'DD  Auto Private Limited',
'Knight Queen Industries Pvt. Ltd.',
'Speego Vehicles Company Pvt Ltd',
'Speego Vehicles Company Pvt Ltd',
'Nabh Motors Pvt Ltd',
'VGLAN Buildcon Private Limited',
'Shri Ram Autotech Pvt. Ltd',
'JHL Motors Pvt. Ltd',
'SHINE METAL UDYOG PVT LTD(UNIT II)',
'Dilli Electric Auto Pvt. Ltd',
'JIJO Electric wheels pvt .Ltd',
'VVA Auto Industries Pvt. Ltd',
'New Arcana India',
'CLH Gaseous Fuel Applications Pvt Ltd',
'Saera Electric Auto Pvt. Ltd.',
'Green Impex',
'Bestway Agencies Pvt. Ltd',
'TWINKLE TRADECOM PRIVATE LIMITED',
'M.K Enterprises',
'Plaudit Techno India Pvt Ltd',
'MAA Shakti Exim Pvt Ltd',
'Nextstep Engineering (P) Ltd',
'Mini Metro EV LLP',
'Top Team Machines Pvt Ltd',
'Nirmal Utility Services Pvt Ltd',
'Hooghly Motors Pvt. Ltd',
'Altius Technologies',
'Xxplore Automotive Private Limited',
'Attolent Autogroup Pvt Ltd',
'TSM Engineering Pvt. Ltd',
'SPEEDWAYS ELECTRIC',
'Y C ELECTRIC VEHICLE',
'DAVE EXIM (P) LTD',
'Saksham Trading Company',
'Om Balajee Automobile (India) Pvt. Ltd',
'Successpath Marketing Pvt. Ltd',
'Jajodia Exports Pvt. Ltd',
'CHEHAK BATTERIES',
'OK Play India Ltd',
'Siwach Steel Pvt Ltd',
'Kirti Solar Ltd',
'Aditya Sai Industries',
'Goenka Electric Motor Vehicles Pvt. Ltd',
'Jay Ace Technologies Ltd',
'JS Mobileon Private Limited',
'Krishna Engineering Works',
'CEEON INDIA',
'Champion Poly Plast',
'AVON Cycles Ltd',
'Saksham Trading Company',
'Caparo Autotech Ltd',
'Vani Electric Vehicles Pvt Ltd',
'ELITE AUTO ENGINEERS PVT LTD',
'Lawat Motors',
'U.P. Telelinks Ltd',
'Divansu Automobiles Ltd',
'Bestway Agencies Pvt. Ltd',
'HITEK Electric Auto Co.',
'Gayam Motor Works Pvt. Ltd',
'Zeniak Innovation India Ltd',
'Needle Eye Plastic Industries Pvt Ltd',
'Five Elements',
'VRINDA ENTERPRISES',
'Victory Electric International',
'CREATIVE ENGINEERING',
'PRAG MOTORS',
'Juno Castings Pvt. Ltd',
'Sauryaa Sharyo Corporation',
'Nanya Airconn Pvt. Ltd',
'AMAN ELECTRIC VEHICLES',
'Juno Castings Pvt. Ltd',
'S. V. AUTOMOTIVE',
'DYS Impex Pvt Ltd',
'BABA E Vehicles',
'Classic Engineers & Fabricators',
'J.S. Auto (Pvt) Ltd',
'Altius Technologies',
'Bali Auto Industries',
'A3T INCORPORATED',
'CLH Gaseous Fuel Applications Pvt Ltd',
'Pats Motor Corp',
'Caparo Autotech Ltd',
'Energy Electric Vehicles',
'Khemraj Automotive Industries',
'Goodwill HI Precision Works Pvt Ltd',
'Bajaj Implements Private Limited',
'Greenwheels Automobile Pvt. Ltd',
'Atul Auto Ltd',
'Pace Agro Pvt Ltd',
'Various Innovative Systems Hybrid Nano Utilities',
'Unique International',
'Thukral Electric Bikes Pvt. Ltd',
'United Transmovers Pvt. Ltd',
'Om Balajee Automobile (India) Pvt Ltd',
'Aaditya Emotors India Pvt. Ltd',
'Suganji Rara Electric Vehicles Pvt. Ltd',
'HI-TECH Industries',
'Shri Ram Autotech Pvt. Ltd',
'Aparna Industries',
'Bijnor Enterprises',
'SKS Trade India Private Limited',
'Adapt Motors Pvt. Ltd.',
'Allfine Industries Private Limited',
'G- Kon Electric Motor Vehicles Pvt. Ltd.',
'Epower Vehicles Pvt. Ltd',
'Rahul Agro Exports Pvt. Ltd.',
'V. T. Engineering',
'Electra International',
'NB Turned Components Pvt. Ltd',
'Chirag Enterprises',
'Bright Autozone Pvt. Ltd',
'Arman Green Vehicles Private Limited',
'Pari E - Vehicles',
'Caparo Autotech Ltd',
'Energy Electric Vehicles',
'Pats Motor Corp',
'Archit Enterprises',
'Jay Ace Technologies Ltd',
'Y C Electric Vehicle',
'Hotage Corporation India',
'Atut Sangam',
'Mac Auto India',
'Shakti Auto Green',
'Shri Namo Electric Automotive',
'Gurukirpa Industries',
'Sauryaa Sharyo Corporation',
'Asia Body Builders and Manufacturers',
'Shree Siridi Sai Mineral & Exports Pvt. Ltd',
'Khalsa Agencies',
'Atul Auto Ltd',
'Needle Eye Plastic Industries Pvt Ltd',
'Rayon Engineers',
'PVR Petro Chemicals Pvt. Ltd',
'Gayatri Electric Vehicles',
'Sunglow Fab LLP',
'Green Valley Motors',
'A. V. Automotives Pvt. Ltd.',
'NB Turned Components Pvt. Ltd',
'Original Fuel System Pvt. Ltd.',
'Prestantia Creations Private Limited',
'SHIV OM India',
'Accretion Power Autos',
'S.P. Electronics',
'NHD Motors',
'Y C Electric Vehicle',
'Green Kaiketsu Automotive India Pvt. Ltd',
'TSM Engineering Pvt. Ltd',
'Launcher Material Handling Industries',
'TSM Engineering Pvt. Ltd.',
'Naraindass and Sons',
'Jemco Engineering Pvt. Ltd.',
'AVON Cycles Ltd',
'Mini Metro EV LLP',
'Gram Tarang Employability Training Services Pvt. Ltd',
'M.K Enterprises',
'Raj Automotive',
'Thukral Electric Bikes Pvt. Ltd',
'Riya Enterprise',
'Eco-Friendly Electric Vehicle Pvt. Ltd.',
'Kranti International',
'Harsh Trading Company',
'DD Auto Private Limited',
'DD Auto Private Limited',
'Top Team Machines Pvt Ltd',
'BIG BULL TRADER PVT. LTD.',
'Ecogreen Hi-Tech Products (P) Ltd',
'Kirti Solar Ltd',
'OK Play India Ltd',
'Ashwa Electric',
'Sauryaa Sharyo Corporation',
'Victory Electric International',
'Top Team Machines Pvt Ltd',
'Panther Electric Vehicles',
'Ankush Auto Deals',
'Champion Poly Plast',
'Arna  Electric Auto Pvt. Ltd',
'E-Motion Automotive Industry LLP',
'Asia Body Builders and Manufacturers',
'Dilli Electric Auto Pvt. Ltd',
'Rajiv Raj Vehicle Pvt. Ltd',
'Sauryaa Sharyo Corporation',
'Yuvraj International',
'Zeniak Innovation India Ltd',
'Green Star Motors',
'Jaidka Power Systems Pvt. Ltd.',
'Bal Gopal Wheels Private Limited',
'Enigma Automobiles Pvt. Ltd.',
'Green Wheelz (India)',
'Delta Autocorp LLP',
'CART INDIA',
'Jajodia Commodities Pvt Ltd',
'Bajaj Implements Private Limited',
'Original Fuel System Pvt. Ltd.',
'Green Technologies',
'Allfine Industries Private Limited',
'Multi Dimensional Solutions',
'Rasandik Engineering Industries India Ltd',
'Rajesh Steel & Wire Industries',
'MAA Shakti Exim Pvt Ltd',
'Welkin Healthcare Pvt. Ltd.',
'Classic Engineers & Fabricators',
'Naraindass and Sons',
'SSB Industries',
'SKS Trade India Private Limited',
'Adapt Motors Pvt. Ltd.',
'Hindustan Motor Corporation',
'S and J Industries',
'G & G Automotive',
'Divya Enterprises',
'Hundal Industries',
'Ceeon India',
'Hitech Mechanical Works',
'KABMAX Electric Automobiles  Pvt. Ltd',
'H.D. Automotives',
'A. K. Gupta & Co',
'Shriraj Electric Vehicles',
'Veeto Automobiles',
'Terra Motors India Pvt. Ltd',
'Radha Raman Electric Vehicles',
'Kalika Vahan Private Limited',
'Jitendra New EV Tech Pvt. Ltd',
'Sumfonl Auto Traders Pvt. Ltd',
'Rayon Engineers',
'Universal Auto Enterprises',
'M.K Enterprises',
'Mahi Enterprises',
'Diamond E Vehicles',
'Shri Namo Electric Automotive',
'Shri Ram Autotech Pvt. Ltd',
'DD Auto Private Limited',
'Nanya Airconn Pvt. Ltd',
'Hanuman Udyog',
'SSB Industries',
'AVON Cycles Ltd',
'Om Industries',
'Shine Metal Udyog Pvt. Ltd',
'OK Play India Ltd',
'Victory Electric International',
'Chauhan Auto Industries',
'Bright Autozone Pvt. Ltd.',
'KLB Komaki Private Limited',
'Allfine Industries Private Limited',
'Jade Korea Spine Life',
'Mahindra & Mahindra Ltd',
'Premier Esol Technologies',
'Mehar Dattey Group Motors Private Limited',
'Motor and General Sales Private Limited',
'Rajesh Steel & Wire Industries',
'Mullick Three Whellers',
'Bal Gopal Wheels Private Limited',
'Supertech Inc',
'Shreya Engineers',
'Seth Industrial Corporation',
'JSS Engineering Company',
'Ecogreen Hi-Tech Products (P) Ltd',
'Sathi Motors Electric Vehicle Pvt. Ltd',
'Pubang Etron Electric Motor Pvt. Ltd',
'Jitendra New Ev Tech Pvt. Ltd',
'A. V. Automotives Pvt. Ltd',
'Shri Ram Autotech Pvt. Ltd.',
'Aadhya Enterprises',
'Bentinck Industries Private Limited',
'Swastik',
'Zeniak Innovation India Ltd',
'Bareja Automotive',
'A. K. Gupta & Co',
'G Williams Fabrications Ltd',
'General Agencies (KOLKATA) Pvt Ltd',
'Goenka Electric Motor Vehicles Pvt. Ltd',
'SN Solar Energy',
'Deep Drawn Technologies',
'Punjab Body Builders',
'Sen and Pandit Voltage Control Pvt. Ltd',
'Eco Smart Vehicles Pvt. Ltd.',
'Macneill Engineering Limited',
'D S F Industries Pvt. Ltd',
'Vishwakarma GNG Industry',
'Goodwill HI Precision Works Pvt Ltd',
'Skyride Automotive',
'Dynavolt Technology (India) Limited',
'Goodwill HI Precision Works Pvt Ltd',
'Purva Udyog Pvt. Ltd.',
'Diwa Green Technology Private Limited',
'Trupart Automotive India Pvt. Ltd.',
'Sutlej E-Motive LLP',
'Mali Enterprises',
'Haarish Automotives (OPC) Pvt. Ltd.',
'Praakram Auto & Construction Equipments',
'Deltek Enterprises Pvt Ltd',
'Krishna Vehicals',
'VVA Auto Industries Pvt. Ltd.',
'Kuku Automotives',
'Nova Automotive Technologies Pvt. Ltd',
'Mehar Dattey Group Motors Private Limited',
'Cart India',
'Jessun Techno Private Limited',
'Wox Coolers Pvt. Ltd.',
'Twashtre Automotive Private Limited',
'Simplex Electrical Engineering Pvt Ltd',
'Apsara Enterprise',
'Kanha Electric Vehicles',
'Pubang Etron Electric Motor Pvt. Ltd',
'Multi Dimensional Solutions',
'Truz Industries',
'Aaditya Garbage Products Pvt Ltd',
'Durable Flanges Pvt. Ltd',
'Star Bull E Motors',
'Anjali Traders',
'Pari Metro E Rickshaw',
'Six Senses Automotive Pvt. Ltd',
'E Xtra Fast Solution',
'Chandak E Automobiles LLP',
'Motrac Motors Private Limited',
'Rajesh Steel & Wire Industries',
'Ramon Industries',
'Shine Metal Udyog Pvt. Ltd.  (Unit Ii)',
'Singhal Enterprises',
'KABMAX Electric Automobiles  Pvt. Ltd.',
'Seth Industrial Corporation',
'Nova Automotive Technologies Pvt. Ltd',
'Arihant Enterprises',
'Chirag Enterprises',
'Two Friends Auto Electric Co.',
'Unique Enterprises',
'Sirf India Vehicle Pvt. Ltd',
'Bright Autozone Pvt. Ltd',
'Gayatri Electric Vehicles',
'I – Moto Greens Pvt. Ltd.',
'APM Auto Sales',
'Nipun Sanyantra Pvt. Ltd',
'Dilli Electric Auto Pvt. Ltd',
'VSL Industries',
'D S F Industries Pvt. Ltd',
'Duke Auto India',
'Godawari Techno Solutions Pvt Ltd.',
'Indian Motors',
'Swastika Polymers Pvt. Ltd',
'Asha Tilak Ventures Pvt Ltd',
'TSR Trade COM',
'Kamaz Industries.',
'UMA Motors',
'Various Innovative Systems Hybrid Nano Utilities',
'Olympus Industries Private Limited',
'KGN Industries',
'Shri Namo Electric Automotive',
'SE Asia CO.',
'Motor and General Sales Private Limited',
'Lohia Auto Industries',
'Mohan General Trading Company',
]

from googlesearch import search
my_list = []
for j in websites:
	for x in  search(j,stop=5):
		my_list.append(x)

import csv
with open("info", "w") as output:
    writer = csv.writer(output, lineterminator='\n')
    for val in my_list:
        writer.writerow([val])  


# for x in df['gg']:
# 		function(urlopen(x))